@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedCoordiMate" as VersionedCoordiMate MODEL_COLOR
end box

[-> Model : undoCoordiMate()
activate Model

Model -> VersionedCoordiMate : undo()
activate VersionedCoordiMate

VersionedCoordiMate -> VersionedCoordiMate :resetData(ReadOnlyCoordiMate)
VersionedCoordiMate --> Model :
deactivate VersionedCoordiMate

[<-- Model
deactivate Model

@enduml
